### ISSUE TITLE
not saving

### ISSUE THREAD

**Issue by ugintl** [hypeJunction/hypeInbox#15]
When I try to save inbox settings, it gives a white page. when I go back to settings, it shows error  Form is missing __token or __ts fields. I have disabled friends feature and installed followers plugin. "Relationship of the sender to the group that the recipient is a member of" and "relationship to recipient" dropdown is empty.

**Comment by Tavalon** [comment]
Same problem .... click save for inbox settings and then it gives a white page :(

**Comment by hypeJunction** [comment]
resolved
