### ISSUE TITLE
no way to select messages in the inbox list

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeInbox#18]
the 'mark read' function cannot be used since there is no way to mark messages as 'selected'

**Comment by hypeJunction** [comment]
There are checkboxes. Must be an issue with your theme. Reopen if you can confirm this with aalborg.

**Comment by propertunist** [comment]
oh ok - i can't test this at the moment as it requires hype lists which is producing js errors for me here.

**Comment by hypeJunction** [comment]
Re: hypeLists, I have seen the error you have mentioned, and will look into it soon, I hope
