### ISSUE TITLE
Send a message to multiple Elgg users or to a group.

### ISSUE THREAD

**Issue by jtraulle** [hypeJunction/hypeInbox#19]
Hello,

I try to make a link to send a message to multiple Elgg users or to a group into Elgg.
Right now, I can use ```/messages/compose?send_to=<guid>``` URL to pre-fill the field To: for a single Elgg user but I cannot figure out how to pre-fill with multiple users or to a particular existing Elgg group.

How can I achieve that ?

Thanks for your help :smile:

**Comment by hypeJunction** [comment]
Try `/messages/compose?send_to[]=<guid1>&send_to[]=<guid2>`

**Comment by jtraulle** [comment]
It works, thanks :smiley:
