### ISSUE TITLE
Top bar notification

### ISSUE THREAD

**Issue by starphysique** [hypeJunction/hypeInbox#20]
No indication of message received when multiple recipients is utilized. It also does not indicate that the message is new (different background color). It works fine (i.e. number indictor) when single recipient is used.

Elgg 2.01

**Comment by DaveONchE** [comment]
How do I modify the Topbar Menu Icon in my own plugin so as not to mess with the plugins core files?? I tried to unregister the Hookhandler in my plugin start.php but the use of $this->hooks in my start.php returns fatal error. Would it be possible to override the setupTopbarMenu hookhandler with my plugin or I will just have to apply the modificaation directly from the plugin?? I want to use $text = "<i class=\"fa fa-envelope fa-lg\"></i>" and also 'priority' => 100, 'section' => 'alt', in my modification. Thank you.

**Comment by DaveONchE** [comment]
I mean $text = "< i class=\"fa fa-envelope fa-lg\"></i>"

**Comment by hypeJunction** [comment]
You can register a new hook for `'register','menu:topbar'` and filter the menu items as you please.
You can unregister the hook by rewriting callback to `hypeInbox()->hook->setupTopbarMenu()`

**Comment by DaveONchE** [comment]
Thanks! I was able to unregister it using elgg_unregister_plugin_hook_handler('register', 'menu:topbar', '\hypeJunction\Inbox\HookHandlers::setupTopbarMenu'); Now I have registered a new hook and trying to filter the menu items but am still getting fatal error for using $count = $this->model->countUnreadMessages (); in my plugin's start.php

**Comment by hypeJunction** [comment]
use hypeInbox()->model->countUnreadMessages()

**Comment by DaveONchE** [comment]
Cool!! Its perfect now.............Thanks a million.
