### ISSUE TITLE
[Question] Delete messages type

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeInbox#23]
Hi Ismayil, I´ve manually added "Site Messages (__notification)" messajes type, but I can´t find how to delete this added type. How can I delete it?

**Comment by hypeJunction** [comment]
I don't you think you can as matches magic type name. You need to unserialize the plugin setting, unset the key and save.

**Comment by insideth** [comment]
Solved in elgg_private_settings -> message_types
Thanks!
