### ISSUE TITLE
Forward seems not to work

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeInbox#24]
Hello,
when trying to forward on page /messages/forward/769881/ 
error "Page not found"
This plugin's 6.1.0, Elgg 2.3.1
Cheers

**Comment by hypeJunction** [comment]
Works for me. Flush the caches.

**Comment by michelesbw** [comment]
Sorry, since this is a new feature I didn't imagine cache could be involved. Works now

**Comment by hypeJunction** [comment]
It added a new resource view

**Comment by michelesbw** [comment]
Yep, that's why, being it new, I could not think of cached stuff :) ...but surely there's something I haven't understood 100% about caching

**Comment by hypeJunction** [comment]
We have system cache that caches view order and locations, so it doesn't have to scan all folders for views on each request
