### ISSUE TITLE
Message's recipient can't access via email link

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeInbox#25]
Hello,
lately recipients' accessing their messages via email links (ie. /messages/read/834900#elgg-object-834900) get a "You have not sufficient permissions to view this page" even if they0re logged in.
Tested with Elgg 2.3.3 and hypeinbox 6.1.0

**Comment by RiverVanRain** [comment]
Tested this scenario with hypeInbox v7.0 on Elgg 2.3.4 right now -- all works very well, no this issue.
