### ISSUE TITLE
#inbox-popup not opening

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeInbox#26]
Hello,
Elgg 2.3.3, hypeinbox 7, when clicking on the envelope icon the popup doesn't open but all the rest seems to work as a charm. Nothing in error_log, tell me what else I can check to give you more details.
Cheers
M

**Comment by hypeJunction** [comment]
Hm, I must have broken it with the hypeUI integration.

**Comment by michelesbw** [comment]
Forgot to mention that the click doesn't bring to actual inbox either so users can access it only by typing the address manually.
Cheers

**Comment by hypeJunction** [comment]
Everything works on my end.

**Comment by michelesbw** [comment]
Just to add my experience: upon logging in the link works but soon after surfing the site it doesn't anymore. Cheers
